version: '3.3'
services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    image: openspeedtest/latest
    networks:
    - tunnel-network


networks:
  tunnel-network:
    name: tunnel-network
