version: '3.7'
services:
  portainer_agent:
    image: 'portainer/agent:2.18.2'
    container_name: portainer_agent
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    restart: always
    ports:
      - '9001:9001'
networks:
  tunnel-network:
    name: tunnel-network